### ISSUE TITLE
Various other improvements from meeting

### ISSUE THREAD

**Issue by Zukkari** [Zukkari/nirdizati-training-ui#119]
- ~Create tooltips for training parameters. These will be provided by @verenich later. Currently I should implement some kind of engine that will be able to parse those tooltips from configuration.~
- ~When user uploads the log, then after we redirect user to training page, the newly uploaded log should be selected in training view.~
- ~Replace generate button with hyperlink, so user does not have an urge to click it.~
- ~Look into drag and drop functionality for file upload~
- ~Remove ```.XES``` support from labels as it is not currently supported.~

**Comment by verenich** [comment]
Tooltips (the **exact** text that needs to be put):
**Bucketing** - this is how you want to group process traces into _buckets_. A separate predictor will be trained for each bucket.

- Zero - Discard grouping, train a single predictor using all available process traces.
- State based - group traces according to the state (decision point) they have reached so far, one predictor for each state. Note training will take longer for processes with complicated process models.
- Clustering - group similar traces using k-means clustering, one predictor for each cluster.
- Prefix leng**th** based - group traces according to their length. The _n_-th bucket will consist of traces that are at least _n_ events long.

**Encoding** - this is how you want to encode traces from the same bucket into fixed-size feature vectors  

- Last state - concatenate case attributes + attributes of the latest executed event
- Frequency - concatenate case attributes + counts of categorical attributes (activities, resources, etc.) + min/average/max/sum of numerical attributes (cost, time since case start, etc.)
- Combined - last state + frequency
- Index-based - concatenate case attributes + attributes of **each** executed event. The only encoding that is lossless. It can **only** be used with prefix-length bucketing

**Prediction method** - this is the machine learning algorithm that is used to fit a predictive model.
- [Random forest](https://en.wikipedia.org/wiki/Random_forest)
- [Gradient boostingt](https://en.wikipedia.org/wiki/Gradient_boosting)
- [Decision tree](https://en.wikipedia.org/wiki/Decision_tree)
- [XGBoost](https://en.wikipedia.org/wiki/Xgboost)
